"""Add transaction_type column

Revision ID: eee6f518e61f
Revises: 883cd2b72bbb
Create Date: 2024-03-24 14:14:58.847491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eee6f518e61f'
down_revision: Union[str, None] = '883cd2b72bbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('trasaction_type', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'trasaction_type')
    # ### end Alembic commands ###
